# Generated by Django 4.2.3 on 2023-08-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PollApp', '0003_remove_pollrecord_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollrecord',
            name='vote_four',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollrecord',
            name='vote_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollrecord',
            name='vote_three',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollrecord',
            name='vote_two',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
